In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

In [2]:
df = pd.read_csv("../data/processed/anime_cleaned.csv")

In [3]:
features_df = df[
    [
        "mal_id",
        "title",
        "title_english",
        "genres",
        "themes",
        "studios",
        "demographics",
        "type",
        "synopsis",
        "url"
    ]
].copy()

In [4]:
features_df.head()

,mal_id,title,title_english,genres,themes,studios,demographics,type,synopsis,url
0,1,Cowboy Bebop,Cowboy Bebop,"Action, Award Winning, Sci-Fi","Adult Cast, Space",Sunrise,Unknown,TV,"Crime is timeless. By the year 2071, humanity has expanded across the galaxy, filling the surface of other planets with settlements like those on Earth. These new societies are plagued by murder, ...",https://myanimelist.net/anime/1/Cowboy_Bebop
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,"Action, Sci-Fi","Adult Cast, Space",Bones,Unknown,Movie,"Another day, another bounty—such is the life of the often unlucky crew of the Bebop. However, this routine is interrupted when Faye, who is chasing a fairly worthless target on Mars, witnesses an ...",https://myanimelist.net/anime/5/Cowboy_Bebop__Tengoku_no_Tobira
2,6,Trigun,Trigun,"Action, Adventure, Sci-Fi",Adult Cast,Madhouse,Shounen,TV,"Vash the Stampede is the man with a $$60,000,000,000 bounty on his head. The reason: he's a merciless villain who lays waste to all those that oppose him and flattens entire cities for fun, garner...",https://myanimelist.net/anime/6/Trigun
3,7,Witch Hunter Robin,Witch Hunter Robin,"Action, Drama, Mystery, Supernatural",Detective,Sunrise,Unknown,TV,"Though hidden away from the general public, Witches—those with supernatural powers—have always existed in human societies. Neither numerous nor inherently evil, Witches are nonetheless capable of ...",https://myanimelist.net/anime/7/Witch_Hunter_Robin
4,8,Bouken Ou Beet,Beet the Vandel Buster,"Action, Adventure, Fantasy",Unknown,Toei Animation,Shounen,TV,"It is the dark century and the people are suffering under the rule of the devil, Vandel, who is able to manipulate monsters. The Vandel Busters are a group of people who hunt these devils, and amo...",https://myanimelist.net/anime/8/Bouken_Ou_Beet

In [5]:
features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28491 entries, 0 to 28490
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   mal_id         28491 non-null  int64
 1   title          28491 non-null  str
 2   title_english  12232 non-null  str
 3   genres         28491 non-null  str
 4   themes         28491 non-null  str
 5   studios        28491 non-null  str
 6   demographics   28491 non-null  str
 7   type           28491 non-null  str
 8   synopsis       23443 non-null  str
 9   url            28491 non-null  str
dtypes: int64(1), str(9)
memory usage: 14.5 MB

In [6]:
text_columns = [
    "genres",
    "themes",
    "studios",
    "demographics",
    "type"
]


for col in text_columns:
    features_df[col] = (
        features_df[col]
        .str.lower()
        .str.replace(",", " ", regex=False)
        .str.replace(" ", "_", regex=False)
    )

In [7]:
features_df["synopsis"] = (
    features_df["synopsis"]
    .fillna("")
    .str.lower()
)

In [8]:
features_df.head()

,mal_id,title,title_english,genres,themes,studios,demographics,type,synopsis,url
0,1,Cowboy Bebop,Cowboy Bebop,action__award_winning__sci-fi,adult_cast__space,sunrise,unknown,tv,"crime is timeless. by the year 2071, humanity has expanded across the galaxy, filling the surface of other planets with settlements like those on earth. these new societies are plagued by murder, ...",https://myanimelist.net/anime/1/Cowboy_Bebop
1,5,Cowboy Bebop: Tengoku no Tobira,Cowboy Bebop: The Movie,action__sci-fi,adult_cast__space,bones,unknown,movie,"another day, another bounty—such is the life of the often unlucky crew of the bebop. however, this routine is interrupted when faye, who is chasing a fairly worthless target on mars, witnesses an ...",https://myanimelist.net/anime/5/Cowboy_Bebop__Tengoku_no_Tobira
2,6,Trigun,Trigun,action__adventure__sci-fi,adult_cast,madhouse,shounen,tv,"vash the stampede is the man with a $$60,000,000,000 bounty on his head. the reason: he's a merciless villain who lays waste to all those that oppose him and flattens entire cities for fun, garner...",https://myanimelist.net/anime/6/Trigun
3,7,Witch Hunter Robin,Witch Hunter Robin,action__drama__mystery__supernatural,detective,sunrise,unknown,tv,"though hidden away from the general public, witches—those with supernatural powers—have always existed in human societies. neither numerous nor inherently evil, witches are nonetheless capable of ...",https://myanimelist.net/anime/7/Witch_Hunter_Robin
4,8,Bouken Ou Beet,Beet the Vandel Buster,action__adventure__fantasy,unknown,toei_animation,shounen,tv,"it is the dark century and the people are suffering under the rule of the devil, vandel, who is able to manipulate monsters. the vandel busters are a group of people who hunt these devils, and amo...",https://myanimelist.net/anime/8/Bouken_Ou_Beet

In [9]:
boilerplate = (
    "No synopsis has been added for this series yet.\n\n"
    "Click here to update this information."
)

features_df["synopsis"] = (
    features_df["synopsis"].replace(boilerplate, "")
)

In [10]:
features_df["combined_features"] = (
    features_df["genres"] + " " +
    features_df["themes"] + " " +
    features_df["studios"] + " " +
    features_df["demographics"] + " " +
    features_df["type"] + " " +
    features_df["synopsis"]
)

In [11]:
features_df[
    ["title", "combined_features"]
].head()

,title,combined_features
0,Cowboy Bebop,"action__award_winning__sci-fi adult_cast__space sunrise unknown tv crime is timeless. by the year 2071, humanity has expanded across the galaxy, filling the surface of other planets with settlemen..."
1,Cowboy Bebop: Tengoku no Tobira,"action__sci-fi adult_cast__space bones unknown movie another day, another bounty—such is the life of the often unlucky crew of the bebop. however, this routine is interrupted when faye, who is cha..."
2,Trigun,"action__adventure__sci-fi adult_cast madhouse shounen tv vash the stampede is the man with a $$60,000,000,000 bounty on his head. the reason: he's a merciless villain who lays waste to all those t..."
3,Witch Hunter Robin,"action__drama__mystery__supernatural detective sunrise unknown tv though hidden away from the general public, witches—those with supernatural powers—have always existed in human societies. neither..."
4,Bouken Ou Beet,"action__adventure__fantasy unknown toei_animation shounen tv it is the dark century and the people are suffering under the rule of the devil, vandel, who is able to manipulate monsters. the vandel..."

In [12]:
recommendation_df = features_df[
    [
        "mal_id",
        "title",
        "combined_features",
        "url"
    ]
].copy()

In [13]:
recommendation_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28491 entries, 0 to 28490
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   mal_id             28491 non-null  int64
 1   title              28491 non-null  str
 2   combined_features  28491 non-null  str
 3   url                28491 non-null  str
dtypes: int64(1), str(3)
memory usage: 13.0 MB

In [14]:
recommendation_df.to_csv(
    "../data/processed/anime_recommendation_features.csv",
    index=False
)